print("1. Mix 500g of Flour, 10g Yeast and 300ml Water in a bowl.\n")
print("2. Knead the dough for 10 minutes.\n")
print("3. Add 3g of Salt.\n")
print("4. Leave to rise for 2 hours.\n")
print("5. Bake at 200 degrees C for 30 minutes.\n")
